# This config provides two commands for flashing/running:
#
# `cargo run`:      normal probe-rs run, with `defmt::monitor!()` calls disabled
# `cargo monitor`   flashes with the defmt-monitor TUI, with `defmt::monitor!()` calls enabled

[alias]
monitor = [
    "run",
    "--config", "env.DEFMT_MONITOR='on'",
    "--config", "target.thumbv7em-none-eabihf.runner='./.scripts/run.sh monitor'",
]

[env]
# DEFMT_LOG doesn't affect defmt_monitor::monitor!() calls
DEFMT_LOG = "trace"

# turns off defmt_monitor::monitor!() macros by default since we have cargo monitor for that
DEFMT_MONITOR = "off"
# firmware target
FIRMWARE_CHIP = "STM32F446RETx"

[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
# Checks the required tool is installed before handing over. See .scripts/run.sh.
runner = "./.scripts/run.sh console"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]
